version: "3.2"
services:
  php:
    image: php:8.2-apache
    volumes:
      - ./html/:/var/www/html/:ro
    ports:
      - 8000:80
    networks:
      - backend
    command:
      - /bin/sh
      - -c
      - |
        docker-php-ext-install mysqli
        apt-get update \
            && apt-get install -y libzip-dev \
            && docker-php-ext-install zip
        apachectl -D FOREGROUND
 
  mysql:
    image: mysql:5.6.40
   
    networks:
      - backend
 
    environment:
      MYSQL_DATABASE: maindb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
 
    volumes:
      #- ./mysql/maindb.sql:/docker-entrypoint-initdb.d/maindb.sql
      - ./mysql/persist/mysql-db-storage:/var/lib/mysql
 
  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - backend
    ports:     
      - 8001:80
 
    depends_on:
      - mysql
 
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      #- PMA_ARBITRARY=1
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      #- PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
 
networks:
  frontend:
  backend: